### ISSUE TITLE
Fix stub path for non-Windows environments

### ISSUE THREAD

**Issue by jcandan** [leandrocfe/filament-apex-charts#1]
### Problem

The following exception occurs:

```
file_get_contents(/app/vendor/leandrocfe/filament-apex-charts/src/CommandsLine.stub): Failed to open stream: No such file or directory
```

#### Steps to reproduce

Within a Linux container, run `php artisan make:filament-apex-charts BlogPostsChart`.

### Proposed resolution

It is my understanding that Windows supports forward slashes.

Update `getStubPath` to use forward slashes:

```
        $path = Str::of(__DIR__)
            ->replace('src/Commands', 'stubs/')
```

If this does not work on Windows, then this works too:

```
        $path = Str::of(__DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'stubs'.DIRECTORY_SEPARATOR)
```

Though, judging by [FortifyServiceProvider.php](https://github.com/laravel/fortify/blob/eb97f088c2a3e010e76cb58e9406427d1cee8de3/src/FortifyServiceProvider.php#L128), this seems like the way to go:

```
        $path = Str::of(__DIR__.'../../stubs/')
```

**Comment by leandrocfe** [comment]
Thank you. Fixed: https://github.com/leandrocfe/filament-apex-charts/releases/tag/0.1.2
