### ISSUE TITLE
Widget Register Issue

### ISSUE THREAD

**Issue by MarJose123** [leandrocfe/filament-apex-charts#27]
I've create a widget and I used the on an Edit or View page, however the Filament still showing that to the dashboard even if the widget is not registered on the filament config.

Not sure if this issues is on the plug-in or on the filament it self.

**Comment by MarJose123** [comment]
I resolved my issues by changing the Pages/PageName/Widgets namespace. Then it wont be autodiscovered for the dashboard.

I think the plugin need enhancement to ask if where the widget need to be placed.

**Comment by erashdan** [comment]
+1
