### ISSUE TITLE
Problem in light mode

### ISSUE THREAD

**Issue by gotzsys** [leandrocfe/filament-apex-charts#28]
When I change from dark to light mode, the colors are set correctly.
![image](https://github.com/leandrocfe/filament-apex-charts/assets/13874850/9183e219-1e0a-4074-8275-aa263afd776d)

However, when I refresh the page, this problem occurs.
![image](https://github.com/leandrocfe/filament-apex-charts/assets/13874850/5433b846-648e-49be-947c-0b6a06a1138a)

**Comment by andrewdwallo** [comment]
Can confirm that this does happen sometimes. I tried to use the "title" option and the same thing happened.

**Comment by Valpuia** [comment]
Check this out.. I submit issue but found a solution

https://github.com/leandrocfe/filament-apex-charts/issues/25#issuecomment-1574629367

**Comment by andrewdwallo** [comment]
It's not really a solution though. `#9ca3af` is essentially the only color that you can use for legend labels, etc... only because the color looks okay in both light and dark. I think it would be a lot better if dark mode was actually supported with chart text, but I'm not sure how that would be done unless the package owner decided to override something from apex charts.

**Comment by andrewdwallo** [comment]
So, in my opinion, it may not be an issue, but I think it is definitely a flaw...

**Comment by gotzsys** [comment]
The problem is here...

![image](https://github.com/leandrocfe/filament-apex-charts/assets/13874850/b687f2ce-0ca8-4cf8-8930-8f87604bd6be)

```
localStorage.getItem('theme') || (document.documentElement.classList.contains('dark') ? 'dark' : 'light')
```

**Comment by andrewdwallo** [comment]
I'm not sure if that is the actual issue but I actually found a solution by overriding the CSS class of whatever I am trying to use in `filament.css` like this:

```
.apexcharts-title-text {
    fill: #111827;
}

.dark .apexcharts-title-text {
    fill: #ffffff;
}
```

This actually looks promising to me for many things.

**Comment by gotzsys** [comment]
Theme set to dark mode
![image](https://github.com/leandrocfe/filament-apex-charts/assets/13874850/63bd78f4-5d4f-4ec0-9038-6caadc2edc74)

![image](https://github.com/leandrocfe/filament-apex-charts/assets/13874850/7dc45af2-b022-4e90-8a51-08996a665693)

Theme changed to light mode.
![image](https://github.com/leandrocfe/filament-apex-charts/assets/13874850/3ba930a2-762b-41c1-963e-dec6f2a30dd1)
![image](https://github.com/leandrocfe/filament-apex-charts/assets/13874850/783b1494-0dc0-49d2-b0e8-e396518ef7a1)

**Comment by leandrocfe** [comment]
> Theme set to dark mode
> ![image](https://github.com/leandrocfe/filament-apex-charts/assets/13874850/63bd78f4-5d4f-4ec0-9038-6caadc2edc74)
> 
> ![image](https://github.com/leandrocfe/filament-apex-charts/assets/13874850/7dc45af2-b022-4e90-8a51-08996a665693)
> 
> Theme changed to light mode.
> ![image](https://github.com/leandrocfe/filament-apex-charts/assets/13874850/3ba930a2-762b-41c1-963e-dec6f2a30dd1)
> ![image](https://github.com/leandrocfe/filament-apex-charts/assets/13874850/783b1494-0dc0-49d2-b0e8-e396518ef7a1)
> 
> @leandrocfe, procede?
> 

Sim, eu vou remover e deixar somente pela classe. Tenho umas melhorias pra lançar junto com isso. Acho que até a próxima semana 👍

**Comment by gotzsys** [comment]
Boa, muito obrigado @leandrocfe !
Abraço e bom final de semana

**Comment by leandrocfe** [comment]
> Boa, muito obrigado @leandrocfe !
> Abraço e bom final de semana

Valeu. Bom fim de semana

**Comment by leandrocfe** [comment]
Hi @gotzsys,
Would you like to try this version?
```bash
composer require leandrocfe/filament-apex-charts:"^2.0"
```

**Comment by gotzsys** [comment]
Hi @leandrocfe, sorry for the late reply, the adjustment worked out well, thank you very much!
