### ISSUE TITLE
Lazy Load Widgets

### ISSUE THREAD

**Issue by KyleWLawrence** [leandrocfe/filament-apex-charts#3]
Would you be open to integrating this project with Livewire's [deferred loading feature](https://rias.be/blog/keep-your-filament-admin-dashboard-fast-by-lazy-loading-widgets)?

If so, would you like me to create a pull request for the changes?

I'm using a 3rd party API to populate the APEX Charts, which makes the page extremely slow to load on the first time when the data is not cached, but the deferred loading feature is a nice fix.

**Comment by leandrocfe** [comment]
> Would you be open to integrating this project with Livewire's [deferred loading feature](https://rias.be/blog/keep-your-filament-admin-dashboard-fast-by-lazy-loading-widgets)?
> 
> If so, would you like me to create a pull request for the changes?
> 
> I'm using a 3rd party API to populate the APEX Charts, which makes the page extremely slow to load on the first time when the data is not cached, but the deferred loading feature is a nice fix.

Hi, sure! I'll check more about your post and I let you know. Thank you

**Comment by KyleWLawrence** [comment]
Thanks! Look forward to hearing back! And of course I'm willing to do the pull request if you're interested in seeing my proposed implementation.

**Comment by leandrocfe** [comment]
Nice! I'll send an update until tomorrow and I let you know 👌
