### ISSUE TITLE
Pie chart too squeezed on mobile

### ISSUE THREAD

**Issue by ziming** [leandrocfe/filament-apex-charts#35]
See screenshot. It will be nice if apex package pie chart be more mobile friendly like https://github.com/jonquihote/filament-static-chart-widgets

![CleanShot 2023-08-07 at 21 43 45](https://github.com/leandrocfe/filament-apex-charts/assets/679513/a5b6ad50-e424-4fe3-beb9-d9268a41ca99)

**Comment by leandrocfe** [comment]
maybe you can use the responsive option
https://apexcharts.com/docs/options/responsive/

**Comment by leandrocfe** [comment]
Please check the new version and open a new issue if it was necessary.
If you published the views, remove it and try again.
