### ISSUE TITLE
Laravel can't locate Component

### ISSUE THREAD

**Issue by kiritoriq** [leandrocfe/filament-apex-charts#38]
Hi,

I've been upgraded package from v1 to v2. But after i publish the views and try to run in filament it send me this error 
![image](https://github.com/leandrocfe/filament-apex-charts/assets/52488419/856edad7-5aa2-4521-b231-6603fee1d29e)

Am i missing something?

**Comment by leandrocfe** [comment]
Hi, just remove the folder published.

Regards,
Leandro

Em sex., 18 de ago. de 2023 05:11, Ahmad Thoriq ***@***.***>
escreveu:

**Comment by kiritoriq** [comment]
Hi, yep your solutions is working. But for now, i'm facing new issue. I've created stacked bar, but the xaxis.categories seems not showing. At first i tot it's my code, but when i try to use static array it's same, still doesnt show
![image](https://github.com/leandrocfe/filament-apex-charts/assets/52488419/b7871282-eba5-45e0-a9ee-9b1bc7a30bd3)

Any advice for this?

**Comment by kiritoriq** [comment]
And this is my few code to generate the chart.

`return [
            'chart' => [
                'type' => 'bar',
                'height' => 300,
                'stacked' => true,
                'stackType' => '100%'
            ],
            'series' => FetchTicketCountByAssigneeAction::resolve()->execute(),
            'xaxis' => [
                'categories' => array_map(fn ($value) => $value['name'], FetchPersonAssignedToTicketAction::resolve()->execute()),
                'labels' => [
                    'style' => [
                        'colors' => '#9ca3af',
                        'fontWeight' => 600,
                    ],
                ],
            ],
            'yaxis' => [
                'labels' => [
                    'style' => [
                        'colors' => '#9ca3af',
                        'fontWeight' => 600,
                    ],
                ],
            ],
            'colors' => ['#6366f1'],
            'plotOptions' => [
                'bar' => [
                    'borderRadius' => 3,
                    'horizontal' => true,
                ],
            ],
        ];`

**Comment by crgAdrian** [comment]
same issue

**Comment by crgAdrian** [comment]
> Hi,
> 
> I've been upgraded package from v1 to v2. But after i publish the views and try to run in filament it send me this error ![image](https://user-images.githubusercontent.com/52488419/261543676-856edad7-5aa2-4521-b231-6603fee1d29e.png)
> 
> Am i missing something?

same issue
