### ISSUE TITLE
dropdownOpen not defined

### ISSUE THREAD

**Issue by makzumi** [leandrocfe/filament-apex-charts#43]
Hello, 
Every time I add a chart I get an error where "dropdownOpen" is not defined. This causes charts not to load properly and filters not to work at all.

Version: 
"leandrocfe/filament-apex-charts": "^3.0",

![image](https://github.com/leandrocfe/filament-apex-charts/assets/1649159/137531d5-70d0-451b-b2b5-f56a7212ab8d)

**Comment by leandrocfe** [comment]
If you publish the views, try to remove the folder and run `composer update`
This was fixed

**Comment by makzumi** [comment]
Nope, that didn't work, I tried a couple things:
- What you suggested, deleted the views folder from resources/views/vendor and then ran composer update. Same error
- I uninstalled and reinstalled the package, same error

**Comment by makzumi** [comment]
Yeah, I dumped autoload, clearead all caches, optimized, etc... Same error hmmm....

**Comment by makzumi** [comment]
Found the issue, I'll submit a PR soon

**Comment by makzumi** [comment]
Here's a PR for this issue: #44 
Thanks
