### ISSUE TITLE
Funnel Chart not supported

### ISSUE THREAD

**Issue by KostasKostogloy** [leandrocfe/filament-apex-charts#50]
Apex Docs: https://apexcharts.com/docs/chart-types/funnel-chart/

Chart type introduced on `v3.41.0` https://github.com/apexcharts/apexcharts.js/releases/tag/v3.41.0
(most recent version being `v3.44.0`)

This package is using `v3.36.2` https://github.com/leandrocfe/filament-apex-charts/blob/master/dist/apexcharts.js

**Comment by leandrocfe** [comment]
I'll update it. Thank you

**Comment by leandrocfe** [comment]
@KostasKostogloy, could you update composer and try it please?
https://github.com/leandrocfe/filament-apex-charts/tree/3.0.2

**Comment by KostasKostogloy** [comment]
@leandrocfe it seems to work fine 👍. Thanks

I had a workaround for datalabels formatting (https://github.com/leandrocfe/filament-apex-charts/issues/16#issuecomment-1803378041) which seems to be broken now. You did a small refactor from what I can see.

Unfortunately now I am stuck with `v3.0.1` 😅

**Comment by leandrocfe** [comment]
@KostasKostogloy, could you try the new version please?
https://github.com/leandrocfe/filament-apex-charts/tree/3.1.0

**Comment by KostasKostogloy** [comment]
@leandrocfe It works fine, good job 👍 

A few updates on my code were needed with the new version.

1. The type of `$chartId` changed from `string` to `?string`. eg. `protected static ?string $chartId = 'yourChartId';`. I updated my charts. Heads up, your code examples still use `string`.
2. You now need to register the plugin on your `PanelProvider` (which you already added on the documentation).

Thanks for the update and happy new year!
