### ISSUE TITLE
Chart id is not unique when rendering component in a loop.

### ISSUE THREAD

**Issue by maltebaer** [leandrocfe/filament-apex-charts#57]
If I try to render a Chart Widget in a loop, all of the charts get appended to the first component.

I guess it is due to [`protected static string $chartId = 'apexChart'`](https://github.com/leandrocfe/filament-apex-charts/blob/462df9378572e02d117c6ddef051921789e1f94d/src/Widgets/ApexChartWidget.php#L30) being assigned a default value. Hence

```php
/**
* Retrieves the chart id.
*
* @return string|null The chart id.
*/
protected function getChartId(): ?string
{
    return static::$chartId ?? 'apexChart_'.Str::random(10);
}
```
will never append a random string.

Changing the property to `protected static ?string $chartId` will do the trick but I'm not sure if this leads to unwanted side effects.

<img width="1571" alt="image" src="https://github.com/leandrocfe/filament-apex-charts/assets/29504917/de3672fe-f1a6-46db-a323-48e259b2415e">

If you think making the property nullable will do the trick, I'm happy to submit a PR.

**Comment by leandrocfe** [comment]
@maltebaer thank you!
Check the new version 3.1.1
https://github.com/leandrocfe/filament-apex-charts/releases/tag/3.1.1

**Comment by maltebaer** [comment]
Awesome, it works like charm! Thanks a lot for the quick fix!
