### ISSUE TITLE
Graphs in darkmode

### ISSUE THREAD

**Issue by langeuh** [leandrocfe/filament-apex-charts#6]
Hi 
using the graphs in dark mode, makes labels unreadable
see screenshots
![Screenshot 2023-02-02 at 10 34 25](https://user-images.githubusercontent.com/5647964/216287143-9e0995d3-d2ae-4ee6-b5ed-c0c1720880ad.png)
![Screenshot 2023-02-02 at 10 34 18](https://user-images.githubusercontent.com/5647964/216287147-e8740a09-aedc-4ff7-9717-50fb4fd59a04.png)
vs
![Screenshot 2023-02-02 at 10 34 08](https://user-images.githubusercontent.com/5647964/216287148-6af9308b-a058-4adf-8db2-4468bfbf1790.png)

**Comment by leandrocfe** [comment]
Yes. I've been working in dark theme options. You can add it in your getOptions array:

`
'tooltip' => [
    'theme' => 'dark',
]
`

**Comment by langeuh** [comment]
This only is a partly solution.
The toolbar menu (screenshot 1 ) doesn't get fixed 
and not everybody uses the dark theme

**Comment by leandrocfe** [comment]
You can try:
`
'theme' => [
    'mode' => 'dark',
],
'chart' => [
    'background' => 'inherit',
    'type' => 'bar',
    'height' => 300
],
`

**Comment by langeuh** [comment]
tried it:
toolbar icons and graph labels in light mode disappear

![Screenshot 2023-02-02 at 12 03 51](https://user-images.githubusercontent.com/5647964/216307971-e794b791-2d9d-4c51-a05e-adb532f81121.png)
![Screenshot 2023-02-02 at 12 03 39](https://user-images.githubusercontent.com/5647964/216307976-b1a4b504-30f3-4a17-9465-18f2ccdd4046.png)

**Comment by leandrocfe** [comment]
Dark theme options will be available in future updates

**Comment by leandrocfe** [comment]
Hi @langeuh,
The dark mode is available in 1.0 version.
https://github.com/leandrocfe/filament-apex-charts/releases/tag/1.0.0
