### ISSUE TITLE
Cannot install this package

### ISSUE THREAD

**Issue by alexfleites** [leandrocfe/filament-apex-charts#67]
Hey, do you have any idea why I always try to install this package in my Filament php 2.x project and get this message

![image](https://github.com/leandrocfe/filament-apex-charts/assets/962479/995fe450-82e3-4cfb-b029-a74151915e02)

**Comment by leandrocfe** [comment]
Laravel version >= 9?

**Comment by alexfleites** [comment]
You don't have a version working for Laravel ^8.0... because I need this package.
Thank You!

**Comment by leandrocfe** [comment]
You should update the Laravel version
