### ISSUE TITLE
Component namespacing?

### ISSUE THREAD

**Issue by PieterxJan** [leandrocfe/filament-apex-charts#9]
Hi,

I was wondering if it would be possible to namespace the used components since it is conflicting with components we use in our own project? 

We use `<x-header>` ourselves but since installing your package, this now throws an exception. Therefore, I was wondering whether maybe it would be possible to namespace the components so it would be something like `<x-filament-apex-charts::header>`?

**Comment by leandrocfe** [comment]
Hi @PieterxJan, it is ok now.
Thank you!
